import test,{before,beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {initializeTestEnvironment} from '@firebase/rules-unit-testing';
import {doc,setDoc,getDoc} from 'firebase/firestore';
import {readFile} from 'node:fs/promises';
import {firestoreStore} from '../firebase-rest.mjs';
import {verifyMembership} from '../membership-service.mjs';
import {validateRequest,referencePrefix,PERIOD_MS} from '../payment-policy.mjs';
let env;
const project='demo-netflixpro-billing';
before(async()=>{env=await initializeTestEnvironment({projectId:project,firestore:{host:'127.0.0.1',port:8787,rules:await readFile(new URL('../../firestore.rules',import.meta.url),'utf8')}})});
beforeEach(async()=>env.clearFirestore());
after(async()=>env?.cleanup());
const store=()=>firestoreStore({FIREBASE_PROJECT_ID:project},{baseUrl:'http://127.0.0.1:8787/v1',tokenProvider:async()=>'owner'});
const request=(uid='alice',receipt='TEST123456')=>validateRequest(uid,{planId:'plan_premium',receiptCode:receipt,paymentReference:referencePrefix(uid,'plan_premium')+'a'.repeat(32)});
const lookup=async()=>({amount:1350,gatewayReference:'fixture'});
test('real REST transactions activate atomically, preserve user metadata and retry idempotently',async()=>{
 const now=Date.now();
 await env.withSecurityRulesDisabled(async c=>setDoc(doc(c.firestore(),'users/alice'),{email:'fixture@example.invalid'}));
 const db=store();const first=await verifyMembership(request(),{store:db,lookup,now:()=>now});
 const retry=await verifyMembership(request(),{store:db,lookup:async()=>{throw Error('Replay must not query gateway')},now:()=>now});
 assert.equal(first.subscription.expiresAt,now+PERIOD_MS);assert.equal(retry.subscription.expiresAt,first.subscription.expiresAt);
 assert.equal((await db.get('users/alice')).email,'fixture@example.invalid');
 assert.equal((await db.get('used_receipts/TEST123456')).usedByUserId,'alice');
 assert.equal((await db.get('subscriptions/alice')).expiresAt,first.subscription.expiresAt);
 const client=env.authenticatedContext('alice').firestore();
 const snapshot=await getDoc(doc(client,'users/alice/subscription/current'));
 assert.equal(snapshot.data().updatedAt.toMillis()>0,true);
 assert.equal(snapshot.data().mpesaReceipt,'TEST123456');
});
test('concurrent REST transactions allow exactly one cross-account receipt redemption',async()=>{
 let release;const held=new Promise(resolve=>release=resolve);let entered=0;let notify;const ready=new Promise(resolve=>notify=resolve);
 const gateway=async()=>{if(++entered===2)notify();await held;return lookup()};
 const alice=verifyMembership(request('alice'),{store:store(),lookup:gateway});
 const bob=verifyMembership(request('bob'),{store:store(),lookup:gateway});
 await ready;release();const results=await Promise.allSettled([alice,bob]);
 assert.equal(results.filter(result=>result.status==='fulfilled').length,1);
 assert.equal(results.filter(result=>result.status==='rejected').length,1);
 const db=store();const receipt=await db.get('used_receipts/TEST123456');
 const loser=receipt.usedByUserId==='alice'?'bob':'alice';
 assert.equal(await db.get(`users/${loser}/subscription/current`),null);
});
test('new receipt renewal retains unexpired membership and consumes each receipt once',async()=>{
 const now=Date.now();const db=store();
 await verifyMembership(request(),{store:db,lookup,now:()=>now});
 const renewed=await verifyMembership(request('alice','SECOND1234'),{store:db,lookup,now:()=>now+1000});
 assert.equal(renewed.subscription.expiresAt,now+2*PERIOD_MS);
 await assert.rejects(verifyMembership(request(),{store:db,lookup,now:()=>now+1000}));
 assert.equal((await db.get('users/alice/subscription/current')).expiresAt,renewed.subscription.expiresAt);
});
